include:
  .gitlab-ci-template.yml

flake8_nb:
  extends: ".flake8_nb"

test-3.6:
  extends: ".test-3.6_glx"

build_sdist:
  extends: ".build_sdist"

test_sdist-3.6_glx:
  extends: ".test_sdist-3.6_glx"

build_doc:
  extends: ".build_doc"
  script: # TODO: image needs pandoc
    - apt-get update
    - apt-get -y install pandoc
    - pip install .[doc]
    - python setup.py build_sphinx

pages:
  extends: ".pages"
