include:
  - project: workflow/ewoks/ewoksci
    file: .gitlab-ci-template.yml

flake8_nb:
  extends: .flake8_nb

test-3.6:
  extends: .test-3.6_glx
  script:
    - !reference [.test-3.6_glx, script]
    - python -m pytest -v --pyargs ewokscore.tests
    - python -m pytest -v --pyargs ewoksppf.tests
    - python -m pytest -v --pyargs ewoksdask.tests
    - python -m pytest -v --pyargs ewoksorange.tests
  timeout: 20m

build_sdist:
  extends: .build_sdist

test_sdist-3.7_glx:
  extends: .test_sdist-3.7_glx
  script:
    - !reference [.test_sdist-3.7_glx, script]
    - python -m pytest -v --pyargs ewokscore.tests
    - python -m pytest -v --pyargs ewoksppf.tests
    - python -m pytest -v --pyargs ewoksdask.tests
    - python -m pytest -v --pyargs ewoksorange.tests
  timeout: 20m

test_sdist-3.8_glx-win:
  extends: .test_sdist-3.8_glx-win
  script:
    - !reference [.test_sdist-3.8_glx-win, script]
    - python -m pytest -v --pyargs ewokscore.tests
    - python -m pytest -v --pyargs ewoksppf.tests
    - python -m pytest -v --pyargs ewoksdask.tests
    #- python -m pytest -v --pyargs ewoksorange.tests
  timeout: 20m

test_sdist-3.9_glx:
  extends: .test_sdist-3.9_glx
  script:
    - !reference [.test_sdist-3.9_glx, script]
    - python -m pytest -v --pyargs ewokscore.tests
    - python -m pytest -v --pyargs ewoksppf.tests
    - python -m pytest -v --pyargs ewoksdask.tests
    - python -m pytest -v --pyargs ewoksorange.tests
  timeout: 20m

build_doc:
  extends: .build_doc

pages:
  extends: .pages

assets:
  extends: .assets
