include:
  - project: dau/ci/pyci
    file: .gitlab-ci-template.yml

variables:
  WARNING1: "ignore::DeprecationWarning:jupyter_client.session"
  WARNING2: "ignore::DeprecationWarning:orangecanvas.utils.localization"
  WARNING3: "ignore::DeprecationWarning:orangecanvas.utils.localization.si"
  IGNORE_WARNINGS: "-W ${WARNING1} -W ${WARNING2} -W ${WARNING3}"

flake8_nb:
  extends: .flake8_nb

isort:
  extends: .isort

test-3.8_glx:
  extends: .test-3.8_glx
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: "-W error ${IGNORE_WARNINGS}"

test-3.13_glx:
  extends: .test-3.13_glx
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: "-W error ${IGNORE_WARNINGS}"

build_sdist:
  extends: .build_sdist

test_sdist-3.8_glx-win:
  extends: .test_sdist-3.8_glx-win
  script:
    - !reference [.test_sdist-3.8_glx-win, script]
    - python -m pip install ewokscore[test]
    - python -m pytest -v --pyargs ewokscore.tests
    - python -m pytest -v --pyargs ewoksppf.tests
    - python -m pytest -v --pyargs ewoksdask.tests
    #- python -m pytest -v --pyargs ewoksorange.tests
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: "-W error ${IGNORE_WARNINGS}"
  timeout: 15m

test_sdist-3.9_glx:
  extends: .test_sdist-3.9_glx
  script:
    - !reference [.test_sdist-3.9_glx, script]
    - python -m pip install ewokscore[test]
    - python -m pytest -v --pyargs ewokscore.tests
    - python -m pytest -v --pyargs ewoksppf.tests
    - python -m pytest -v --pyargs ewoksdask.tests
    - python -m pytest -v --pyargs ewoksorange.tests
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: "-W error ${IGNORE_WARNINGS} -W ignore::RuntimeWarning:networkx.utils.backends" #https://github.com/networkx/networkx/issues/7372
  timeout: 15m

test_sdist-3.13_glx:
  extends: .test_sdist-3.13_glx
  script:
    - !reference [.test_sdist-3.13_glx, script]
    - python -m pip install ewokscore[test]
    - python -m pytest -v --pyargs ewokscore.tests
    - python -m pytest -v --pyargs ewoksppf.tests
    - python -m pytest -v --pyargs ewoksdask.tests
    - python -m pytest -v --pyargs ewoksorange.tests
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: "-W error ${IGNORE_WARNINGS}"
  timeout: 15m

build_doc:
  extends: .build_doc

pages:
  extends: .pages

assets:
  extends: .assets

testpypi:
  extends: .testpypi

pypi:
  extends: .pypi
