stages:
  - style
  - test
  - doc
  - deploy

.base:
  only:
    refs:
      - main
      - merge_requests

.style:
  extends: ".base"
  image: "docker-registry.esrf.fr/dau/ewoks:python_3.6"

.doc:
  extends: ".base"
  image: "docker-registry.esrf.fr/dau/ewoks:python_3.6"

flake8:
  stage: style
  extends: ".style"
  before_script:
    - pip install flake8
  script:
    - flake8

.flake8_nb:
  stage: style
  extends: ".style"
  before_script:
    - pip install flake8_nb
  script:
    - flake8_nb

black:
  stage: style
  extends: ".style"
  before_script:
    - pip install black
  script:
    - LC_ALL=C.UTF-8 black --check --safe .

.sphinx:
  stage: doc
  extends: ".doc"
  before_script:
    - pip install .[doc]
  script:
    - python setup.py build_sphinx

.sphinx_and_artifacts:
  stage: doc
  extends: ".sphinx"
  before_script:
    - rm -rf artifacts
    - mkdir artifacts
  after_script:
    - mv build/sphinx/html artifacts/doc
  artifacts:
    paths:
      - artifacts/doc/
    when: on_success
    expire_in: 2h
  only:
    - main

.test:
  stage: test
  extends: ".base"
  before_script:
    # keep for the extensions
  script:
    - pip install pytest-cov
    - pip install --pre .[test]
    - pytest --cov=./ .

.test-3.6:
  extends: ".test"
  image: "docker-registry.esrf.fr/dau/ewoks:python_3.6"

.test-3.6_glx:
  extends: ".test"
  image: "docker-registry.esrf.fr/dau/ewoks:python_3.6_glx"

.test-3.7:
  extends: ".test"
  image: "docker-registry.esrf.fr/dau/ewoks:python_3.7"

.test-3.8:
  extends: ".test"
  image: "docker-registry.esrf.fr/dau/ewoks:python_3.8"

.test-3.9:
  extends: ".test"
  image: "docker-registry.esrf.fr/dau/ewoks:python_3.9"

.deploy:
  stage: deploy
  extends: ".base"
  image: "docker-registry.esrf.fr/dau/ewoks:python_3.6"
  script:
    - rm -rf public
    - mv artifacts/doc public
  after_script:
    - ls -Rl public
  artifacts:
    paths:
      - public
    expire_in: 2h
  only:
    - main
