import logging
from abc import abstractmethod
from typing import Any
from typing import Dict
from typing import List

from . import pip_freeze
from .base_manager import BaseManager
from .base_manager import BaseManagerInfo
from .base_manager import BaseRequirements

logger = logging.getLogger(__name__)


class FreezeManagerInfo(BaseManagerInfo):
    freeze: List[str]


class FreezeRequirements(BaseRequirements):
    manager: FreezeManagerInfo

    def __info__(self) -> str:
        freeze = "\n  ".join(self.manager.freeze)
        return f"{super().__info__()}\nRequirements:\n  {freeze}"


class FreezeManager(BaseManager):
    """Interface for package managers that describe an environment with a
    requirements list in `pip freeze` format.
    """

    def _is_native(self, requirements: BaseRequirements) -> bool:
        """Any requirements list in `pip freeze` format can be installed,
        also when generated by another package manager.
        """
        return isinstance(requirements, FreezeRequirements)

    def _gather_requirements(self) -> Dict[str, Any]:
        freeze = self._freeze().strip().splitlines()
        return {"freeze": freeze}

    def _install_native_requirements(self, requirements: FreezeRequirements) -> bool:
        return self._install_freeze(requirements.manager.freeze)

    def _install_base_requirements(self, requirements: BaseRequirements) -> bool:
        return self._install_freeze(self._freeze_distributions(requirements))

    @abstractmethod
    def _freeze(self) -> str:
        """Requirements of the current environment in `pip freeze` format."""
        pass

    @abstractmethod
    def _install(self, arguments: List[str]) -> None:
        """Install sanitized requirements in `pip freeze` format."""
        pass

    def _install_freeze(self, freeze: List[str]) -> bool:
        if not freeze:
            return False

        self._install(self._arguments(freeze))
        return True

    def _freeze_distributions(self, requirements: BaseRequirements) -> List[str]:
        """
        Pip freeze argument from list of distributions.
        """
        freeze = []
        for dist in requirements.distributions:
            lines, warnings = pip_freeze.freeze_distribution(dist)
            for warning in warnings:
                logger.warning(warning)
            freeze.extend(lines)
        return freeze

    def _arguments(self, freeze: List[str]) -> List[str]:
        arguments, warnings = pip_freeze.sanitize_freeze(freeze)
        for warning in warnings:
            logger.warning(warning)
        return arguments
