"""Tests that apply to all package managers using the `pip freeze` requirements format."""

from typing import Dict
from typing import List
from typing import Optional

import pytest

from ..._requirements.utils.freeze_manager import FreezeRequirements
from ..._requirements.utils.parse import parse_requirements
from .managers import ManagerCase
from .managers import parametrize_freeze_managers
from .utils import freeze_requirements

pytestmark = parametrize_freeze_managers

_DISTRIBUTION = "six"
_VERSION = "1.17.0"
_FREEZE = [f"{_DISTRIBUTION}=={_VERSION}"]


def test_gather_freeze(manager_case, environment):
    manager = manager_case.manager(environment)
    assert manager.gather_requirements().manager.freeze == []

    manager.install_requirements(_requirements(manager_case, _FREEZE))

    assert manager.gather_requirements().manager.freeze == _FREEZE


def test_install_freeze(manager_case, environment):
    manager = manager_case.manager(environment)
    with pytest.raises(RuntimeError, match="package is not installed"):
        _ = environment.get_version(_DISTRIBUTION)

    manager.install_requirements(_requirements(manager_case, _FREEZE))

    assert environment.get_version(_DISTRIBUTION) == _VERSION


def test_install_distributions(manager_case, environment):
    """Without a requirements list, the python distributions are installed."""
    manager = manager_case.manager(environment)
    requirements = _requirements(
        manager_case, [], distributions=[{"name": _DISTRIBUTION, "version": _VERSION}]
    )

    manager.install_requirements(requirements)

    assert environment.get_version(_DISTRIBUTION) == _VERSION


def test_install_foreign_freeze(manager_case, environment):
    """Requirements generated by another package manager using the same format."""
    manager = manager_case.manager(environment)
    requirements = parse_requirements(_FREEZE)  # legacy 'pip freeze' list
    assert requirements.manager.name == "pip"

    manager.install_requirements(requirements)

    assert environment.get_version(_DISTRIBUTION) == _VERSION


def test_install_nothing(manager_case, environment):
    manager = manager_case.manager(environment)
    requirements = _requirements(manager_case, [], distributions=[])

    with pytest.raises(ValueError, match="No distibutions provided to install"):
        manager.install_requirements(requirements)


def _requirements(
    manager_case: ManagerCase,
    freeze: List[str],
    distributions: Optional[List[Dict[str, str]]] = None,
) -> FreezeRequirements:
    return parse_requirements(
        freeze_requirements(manager_case.NAME, freeze, distributions=distributions)
    )
