"""Tests that apply to all package managers."""

from typing import Iterator

import pytest

from ..._requirements import install_requirements
from ..._requirements.utils import base_manager
from ..._requirements.utils import detect
from ..._requirements.utils._supported import get_supported_managers
from ..._requirements.utils.detect import get_manager
from ..._requirements.utils.environment import Environment
from ..._requirements.utils.parse import parse_requirements
from ...errors import AbortException
from .managers import ManagerCase
from .utils import DISTRIBUTIONS
from .utils import EWOKS_DEPENDENCIES
from .utils import PYTHON_VERSION
from .utils import assert_installed
from .utils import assert_not_installed
from .utils import current_metadata
from .utils import manager_requirements


def test_available(manager):
    version = manager.version()
    assert version
    assert version[0].isdigit()


def test_not_available(manager_case, monkeypatch):
    monkeypatch.setattr(manager_case.MANAGER_CLS, "version", lambda self: None)
    with pytest.raises(ValueError, match="not available"):
        get_manager(manager_name=manager_case.NAME)


def test_select_manager(manager_case):
    manager = get_manager(
        manager_name=manager_case.NAME, manager_command=manager_case.command()
    )
    assert isinstance(manager, manager_case.MANAGER_CLS)


def test_is_active(manager):
    assert isinstance(manager.is_active(), bool)


def test_detect_manager(manager_case, uncached_distribution_count, monkeypatch):
    """The package manager that installed the distributions is detected when no
    package manager is active."""
    for manager_cls in get_supported_managers().values():
        monkeypatch.setattr(manager_cls, "is_active", lambda self: False)
    distributions = [
        dist.model_copy(update={"installer": manager_case.INSTALLER})
        for dist in DISTRIBUTIONS
    ]
    monkeypatch.setattr(
        detect,
        "current_requirements",
        lambda: current_metadata(distributions, PYTHON_VERSION),
    )

    manager = get_manager()

    assert isinstance(manager, manager_case.MANAGER_CLS)


@pytest.fixture
def uncached_distribution_count() -> Iterator[None]:
    """The distributions of the current python environment are counted once."""
    detect._manager_distribution_count.cache_clear()
    yield
    detect._manager_distribution_count.cache_clear()


def test_gather_requirements(manager, manager_case, monkeypatch):
    """Requirements are gathered from the current python environment."""
    metadata = current_metadata(DISTRIBUTIONS, PYTHON_VERSION)
    monkeypatch.setattr(base_manager, "current_requirements", lambda: metadata)

    requirements = manager.gather_requirements()

    assert isinstance(requirements, manager_case.MANAGER_CLS.REQUIREMENTS_MODEL)
    assert requirements.manager.name == manager_case.NAME
    assert requirements.manager.version
    assert requirements.python.version == PYTHON_VERSION
    assert requirements.distributions == DISTRIBUTIONS
    assert isinstance(requirements.manager.files, dict)


def test_create_environment(environment):
    assert environment.exists()
    assert environment.python_version() == PYTHON_VERSION
    assert Environment.from_location(environment.location) == environment
    assert_not_installed(environment, DISTRIBUTIONS)


def test_install_native(manager, manager_case, environment):
    """Install with the files generated by the package manager itself."""
    requirements = _requirements(manager_case, native=True)
    assert manager.is_native(requirements, environment)

    manager.install_files(requirements, environment)

    assert_installed(environment, DISTRIBUTIONS)


def test_install_distributions(manager, manager_case, environment):
    """Without files, the python distributions are installed."""
    requirements = _requirements(manager_case, native=False)
    assert not manager.is_native(requirements, environment)

    manager.install_distributions(requirements, environment)

    assert_installed(environment, DISTRIBUTIONS)


def test_install_nothing(manager, manager_case, tmp_path):
    """Nothing is installed so the environment is not needed."""
    requirements = parse_requirements(manager_requirements(manager_case.NAME))
    environment = Environment.at_location(tmp_path)

    with pytest.raises(ValueError, match="No distributions provided to install"):
        manager.install_distributions(requirements, environment)


def test_install_files_failure(fast_manager_case, env_root, monkeypatch):
    """The python distributions are installed when the files of the package manager
    cannot be installed. Both installations are confirmed."""
    requirements = _requirements(fast_manager_case, native=True)

    def install_files(self, requirements, environment) -> None:
        raise RuntimeError("cannot install the files")

    monkeypatch.setattr(fast_manager_case.MANAGER_CLS, "install_files", install_files)
    confirmations = []

    environment = install_requirements(
        requirements,
        env_name="environment",
        env_root=env_root,
        manager_name=fast_manager_case.NAME,
        manager_command=fast_manager_case.command(),
        confirm=confirmations.append,
    )

    assert_installed(environment, DISTRIBUTIONS)
    assert len(confirmations) == 2
    assert "Manager:" in confirmations[0]
    assert "Distributions:" in confirmations[1]
    assert "package manager failed" in confirmations[1]


def test_install_not_confirmed(fast_manager_case, env_root):
    """Nothing is created when an installation is not confirmed. The confirmation
    mentions why the python distributions are installed."""
    requirements = _requirements(fast_manager_case, native=False)
    confirmations = []

    def confirm(description: str) -> None:
        confirmations.append(description)
        raise AbortException()

    with pytest.raises(AbortException):
        install_requirements(
            requirements,
            env_name="environment",
            env_root=env_root,
            manager_name=fast_manager_case.NAME,
            manager_command=fast_manager_case.command(),
            confirm=confirm,
        )

    assert not (env_root / "environment").exists()
    assert "do not provide files" in confirmations[0]


def test_install_without_name(fast_manager_case):
    """A root directory and cleaning do not define an environment on their own."""
    requirements = parse_requirements(manager_requirements(fast_manager_case.NAME))

    with pytest.raises(ValueError, match="requires an environment name"):
        install_requirements(requirements, env_root="/root/of/the/environments")

    with pytest.raises(ValueError, match="requires an environment name"):
        install_requirements(requirements, clean=True)


def test_environment_location(manager, tmp_path):
    """The package manager provides the location of a named environment."""
    default = manager.environment_location("myenv")
    assert default.is_absolute()
    assert default.name == "myenv"
    assert default.parent == manager.environments_root().expanduser()

    in_root = manager.environment_location("myenv", tmp_path)
    assert in_root == tmp_path / "myenv"


def test_install_in_place_not_supported(manager_case, monkeypatch):
    """A package manager that is explicitly requested is not replaced."""
    monkeypatch.setattr(manager_case.MANAGER_CLS, "CAN_INSTALL_IN_PLACE", False)
    requirements = parse_requirements(manager_requirements(manager_case.NAME))

    with pytest.raises(ValueError, match="cannot install in the current"):
        install_requirements(requirements, manager_name=manager_case.NAME)


def test_ewoks_already_installed(manager, manager_case):
    """Ewoks is installed in the current python environment."""
    requirements = parse_requirements(manager_requirements(manager_case.NAME))

    manager.ensure_ewoks(requirements, Environment.current())


def test_add_ewoks(fast_manager, fast_manager_case, fast_environment):
    """Ewoks is added without changing the versions of the requirements it depends
    on."""
    requirements = parse_requirements(
        manager_requirements(
            fast_manager_case.NAME,
            distributions=EWOKS_DEPENDENCIES,
            python_version=PYTHON_VERSION,
        )
    )
    fast_manager.install_distributions(requirements, fast_environment)

    fast_manager.ensure_ewoks(requirements, fast_environment)

    assert fast_environment.distribution_version("ewoks")
    assert_installed(fast_environment, EWOKS_DEPENDENCIES)


def _requirements(manager_case: ManagerCase, native: bool):
    python_version = PYTHON_VERSION
    if native:
        files = manager_case.native_files(DISTRIBUTIONS, python_version)
        if not files:
            pytest.skip(f"{manager_case.NAME} cannot generate its requirement files")
    else:
        files = None
    return parse_requirements(
        manager_requirements(
            manager_case.NAME,
            files=files,
            distributions=DISTRIBUTIONS,
            python_version=python_version,
        )
    )
