"""Tests of installing requirements generated by another package manager."""

import pytest

from ..._requirements.utils.parse import parse_requirements
from .utils import DISTRIBUTIONS
from .utils import PYTHON_VERSION
from .utils import assert_installed
from .utils import manager_requirements


def test_install_foreign_requirements(
    source_manager_case, manager, manager_case, environment
):
    """Requirements generated by one package manager, installed by another one.

    The files of the package manager that generated the requirements are ignored:
    the installed python distributions are used to generate the files of the
    package manager that installs them.
    """
    if source_manager_case.NAME == manager_case.NAME:
        pytest.skip("not a foreign package manager")

    files = source_manager_case.native_files(DISTRIBUTIONS, PYTHON_VERSION)
    if not files:
        pytest.skip(f"{source_manager_case.NAME} cannot generate its requirement files")
    requirements = parse_requirements(
        manager_requirements(
            source_manager_case.NAME,
            files=files,
            distributions=DISTRIBUTIONS,
            python_version=PYTHON_VERSION,
        )
    )

    assert not manager.is_native(requirements, environment)

    manager.install_distributions(requirements, environment)

    assert_installed(environment, DISTRIBUTIONS)
