from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from ewokscore.graph import TaskGraph

from ..._requirements.utils.metadata import from_pip_freeze
from ..._requirements.utils.parse import parse_requirements


def assert_in_graph_requirements(graph: TaskGraph, *distribution_names) -> None:
    assert distribution_names, "no names provides"
    assert "requirements" in graph.graph.graph, "no requirements"
    requirements = parse_requirements(graph.graph.graph["requirements"])

    existing = {distribution.name for distribution in requirements.distributions}
    not_existing = set(distribution_names) - existing
    assert not not_existing, f"{sorted(not_existing)} not in requirements"


def freeze_requirements(
    manager_name: str,
    freeze: List[str],
    distributions: Optional[List[Dict[str, str]]] = None,
) -> Dict[str, Any]:
    """Workflow requirements as generated by a package manager that uses the
    `pip freeze` requirements format.
    """
    requirements = dict(from_pip_freeze.pip_freeze_requirements(freeze))
    requirements["manager"] = {"name": manager_name, "version": "", "freeze": freeze}
    if distributions is not None:
        requirements["distributions"] = distributions
    return requirements
