import platform
import sys
from typing import Any
from typing import Dict
from typing import List
from typing import Mapping
from typing import Optional
from typing import Tuple

from ewokscore.graph import TaskGraph

from ..._requirements.utils.environment import Environment
from ..._requirements.utils.metadata import models
from ..._requirements.utils.parse import parse_requirements

PYTHON_VERSION = platform.python_version()
"""Python version of the environments created by the tests. The version at
runtime is used because a package manager can only provide a python version that
is available on the machine."""


def _pinned(name: str, versions: Mapping[Tuple[int, int], str]) -> models.Distribution:
    """Distribution pinned to a version the running python supports. The versions
    are keyed by the lowest python version they support."""
    version = next(
        version
        for python_version, version in sorted(versions.items(), reverse=True)
        if python_version <= sys.version_info[:2]
    )
    return models.Distribution(name=name, version=version)


DISTRIBUTIONS = [
    _pinned("six", {(3, 8): "1.17.0"}),
    _pinned("iniconfig", {(3, 8): "2.0.0"}),
]
"""Small distributions used to verify that an installation took place. Unlike the
python version, the versions cannot be derived at runtime: they must be exact
versions that a package manager would not install by itself."""

REQUIREMENTS = [f"{dist.name}=={dist.version}" for dist in DISTRIBUTIONS]
"""`DISTRIBUTIONS` as requirements."""

EWOKS_DEPENDENCIES = [
    _pinned("networkx", {(3, 8): "3.1", (3, 10): "3.4.2"}),
    _pinned("packaging", {(3, 8): "24.1"}),
]
"""Older versions of distributions that ewoks depends on, to verify that adding
ewoks to an environment does not change the versions of the requirements."""


def assert_installed(
    environment: Environment, distributions: List[models.Distribution]
) -> None:
    """Every distribution of `distributions` is installed with its exact version."""
    assert _installed_versions(environment, distributions) == {
        dist.name: dist.version for dist in distributions
    }


def assert_not_installed(
    environment: Environment, distributions: List[models.Distribution]
) -> None:
    """No distribution of `distributions` is installed."""
    assert _installed_versions(environment, distributions) == {
        dist.name: None for dist in distributions
    }


def _installed_versions(
    environment: Environment, distributions: List[models.Distribution]
) -> Dict[str, Optional[str]]:
    return {
        dist.name: environment.distribution_version(dist.name) for dist in distributions
    }


def assert_in_graph_requirements(graph: TaskGraph, *distribution_names) -> None:
    assert distribution_names, "no names provides"
    assert "requirements" in graph.graph.graph, "no requirements"
    requirements = parse_requirements(graph.graph.graph["requirements"])

    existing = {distribution.name for distribution in requirements.distributions}
    not_existing = set(distribution_names) - existing
    assert not not_existing, f"{sorted(not_existing)} not in requirements"


def current_metadata(
    distributions: List[models.Distribution],
    python_version: str,
) -> Dict[str, Any]:
    """Metadata of a python environment with few distributions: the current
    environment can have hundreds, which some package managers take minutes to
    resolve.
    """
    return {
        "system": {
            "system": "",
            "release": "",
            "version": "",
            "machine": "",
            "processor": "",
        },
        "python": {
            "version": python_version,
            "implementation": "",
            "compiler": "",
            "build": "",
        },
        "distributions": distributions,
    }


def manager_requirements(
    manager_name: str,
    files: Optional[Dict[str, str]] = None,
    distributions: Optional[List[models.Distribution]] = None,
    python_version: str = "",
) -> Dict[str, Any]:
    """Workflow requirements as generated by a package manager."""
    return {
        "system": {
            "system": "",
            "release": "",
            "version": "",
            "machine": "",
            "processor": "",
        },
        "python": {
            "version": python_version,
            "implementation": "",
            "compiler": "",
            "build": "",
        },
        "distributions": [dist.model_dump() for dist in distributions or list()],
        "manager": {
            "name": manager_name,
            "version": "",
            "files": files or dict(),
        },
    }
